theme = "hugo-paper"
baseURL = "https://philip-khor.github.io/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
title = "Philip's Curve"
publishDir = "../philip-khor.github.io"
disqusShortname = "philips-curve"
  
[menu] 
  [[menu.main]] 
    identifier = "twitter"
    name = "twitter"
    url = "https://twitter.com/philip_khor"
    
  [[menu.main]]
    identifier = "linkedin"
    name = "linkedin"
    pre = '<i class="fab fa-linkedin-in"></i>'
    url = "https://www.linkedin.com/in/philip-khor/"
    
